### ISSUE TITLE
Random window popping up: "NoneType: None"

### ISSUE THREAD

**Issue by Ankilli** [iamjustkoi/LeechToolkit#8]
**Bug/Issue Description**
While doing reviews a window occasionally pops up reading (screenshot attached below)

**Screenshots/Visuals**
<img width="341" alt="grafik" src="https://user-images.githubusercontent.com/89978096/206541422-756d0fe1-91c4-4719-a8cc-a46637b5967d.png">

**System/Debug Info**
    Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.14.1 PyQt 5.14.1
    Platform: Mac 12.6.1
    Flags: frz=True ao=True sv=3
    Add-ons, last update check: 2022-12-08 09:18:50
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    AMBOSS add-on ['0amboss_addon', 2022-06-27T18:14, 'None', '']
    AnKing Note Types Easy Customization ['952691989', 2022-11-22T19:37, 'None', '']
    Anki Simulator ['817108664', 2021-08-07T21:24, 'None', '']
    Anki Zoom ['538879081', 2020-04-04T02:20, 'v1.1.3', '']
    AnkiWebView Inspector ['31746032', 2022-04-08T21:44, 'None', '']
    Asset Manager ['656021484', 2021-08-29T23:07, 'None', '']
    Batch Editing ['291119185', 2019-06-02T20:47, 'None', '']
    BetterSearch ['1052724801', 2022-01-25T23:25, 'None', '']
    Closet For Anki ['272311064', 2022-08-12T10:27, 'None', '']
    Cloze Overlapper for Anki 21 ['109531687', 2021-01-12T04:12, 'None', '']
    Copy notes ['1566928056', 2021-12-24T20:56, 'None', '']
    Cross Profile Search and Import ['310394744', 2019-05-28T18:15, 'None', '']
    Custom Background Image and Gear Icon ['1210908941', 2022-11-28T19:08, 'None', mod]
    Customize Keyboard Shortcuts ['24411424', 2022-09-14T11:12, 'None', '']
    Deadline2 ['723639202', 2021-05-02T06:45, 'None', mod]
    Frozen Fields ['516643804', 2020-03-01T05:12, 'None', '']
    Image Occlusion Enhanced ['1374772155', 2022-04-09T09:15, 'None', '']
    Leaderboard ['41708974', 2022-05-12T11:46, 'None', mod]
    Learning Step and Review Interval Retention ['1949865265', 2022-08-28T22:21, 'None', '']
    Leech Toolkit ['368380974', 54903-10-22T01:10, 'None', '']
    Mini Format Pack ['295889520', 2018-07-24T19:45, 'None', '']
    More Decks Stats and Time Left ['1556734708', 2022-10-09T14:05, 'None', mod]
    Postpone cards review ['1152543397', 2021-02-13T17:47, 'None', '']
    Refocus Card when Reviewing 21 ['1642550423', 2018-09-19T16:14, 'None', '']
    Remaining time for Anki 21 ['1508357010', 2020-12-13T15:14, '20.12.13i151', mod]
    Removes Empty Note Types for 21 ['530953383', 2019-06-12T16:11, 'None', '']
    Reset Card Scheduling ['300884351', 2018-09-18T18:17, 'None', '']
    Resize images in editor ['1103084694', 2021-07-19T08:35, 'None', mod]
    Review Heatmap ['review_heatmap', 2020-04-30T15:23, 'None', '']
    Set Card Ease ['1387847178', 2022-11-17T19:41, 'None', mod]
    Special Fields ['1102281552', 2022-11-22T02:49, 'None', mod]
    Speed Focus Mode auto-alert auto-reveal auto-fail ['1046608507', 2019-06-02T11:11, 'None', '']
    Straight Reward ['957961234', 2022-03-31T21:37, 'None', '']
    Symbols As You Type ['2040501954', 2022-06-08T06:09, 'None', '']
    Transfer scheduling data from one card to another ['94685914', 2020-09-18T11:23, 'None', '']
    True Retention by Card Maturity ['923360400', 2017-08-29T21:00, 'None', '']
    Ze Add Note Id ['886709118', 2021-03-02T21:06, 'None', '']
    ZzLegacy Spelling Police ['1410276506', 2020-03-03T03:13, 'None', mod]
    autoLapseNewInterval  automatically adjust the new interval after a lapse ['372281481', 2022-09-28T09:26, 'None', mod]
    
    ===IDs of active AnkiWeb add-ons===
    1046608507 1052724801 109531687 1102281552 1103084694 1152543397 1210908941 1374772155 1387847178 1410276506 1508357010 1556734708 1566928056 1642550423 1949865265 2040501954 24411424 272311064 291119185 295889520 300884351 310394744 31746032 368380974 372281481 41708974 516643804 530953383 538879081 656021484 723639202 817108664 886709118 923360400 94685914 952691989 957961234
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Advanced Review Bottom Bar ['1136455830', 2022-09-29T15:31, 'None', mod]
    Auto Ease Factor ['1672712021', 2021-03-21T19:11, 'None', mod]
    ImageResizer ['1214357311', 2022-07-15T15:05, 'None', '']
    Legacy ReMemorize ['323586997', 2020-11-20T06:27, 'None', mod]
    Speed Focus Mode ['speed_focus_mode', 2019-06-29T00:35, 'None', '']
    True Retention ['613684242', 2017-11-19T21:43, 'None', '']

**Additional Context**
I use the most recent LeechToolkit-Version 1.1.1-a5

not urgent, can't say how often it happens but quiet rare so far :)

**Comment by Ankilli** [comment]
Well this is basically everything from the moment the error occurred again :)

> JS error /_anki/legacyPageData?id=4669357360:84 Uncaught TypeError: Cannot set property 'title' of null
> JS error /_anki/legacyPageData?id=4669357360:2 Uncaught SyntaxError: Invalid or unexpected token
> JS error /_anki/legacyPageData?id=4669357360:43 Uncaught TypeError: Cannot set property 'innerHTML' of undefined
> JS error /_anki/legacyPageData?id=4669357360:43 Uncaught TypeError: Cannot set property 'innerHTML' of undefined
> JS error /_anki/legacyPageData?id=4669357360:43 Uncaught TypeError: Cannot set property 'innerHTML' of undefined
> JS error /_anki/legacyPageData?id=4669357360:43 Uncaught TypeError: Cannot set property 'innerHTML' of undefined
[...]
> JS error /_anki/legacyPageData?id=4669357360:43 Uncaught TypeError: Cannot set property 'innerHTML' of undefined
> JS error /_anki/legacyPageData?id=4669357360:43 Uncaught TypeError: Cannot set property 'innerHTML' of undefined
> JS error /_anki/legacyPageData?id=4669357360:43 Uncaught TypeError: Cannot set property 'innerHTML' of undefined
> JS error /_anki/legacyPageData?id=4669357360:43 Uncaught TypeError: Cannot set property 'innerHTML' of undefined
> JS error /_anki/legacyPageData?id=4669357360:17 Uncaught TypeError: Cannot read property 'classList' of null

I hope it helps. I will continue to run terminal in the backround and see if anything else comes up :)

**Comment by Ankilli** [comment]
Well, I just reset the settings of the LeechToolkit and now the msg doesn't pop up anymore, or at least only if I play around with the settings again. I guess they are interfering with each other.. ':D

**Comment by Ankilli** [comment]
Unfortunately the message still pops up ocassionally..
BUT! I think I figured out why. As a matter of fact, it looks like it only happens with cards that have been failed at least once (has ≥1 fails in the card's statistics) and when the Leech-counter decreases (back to 0), then the message window "NoneType:None" pops up.
So the addon does it's work (Terminal.app says nothing different than when a leech counter gets decreased from a higher failed number but the error message comes up.

Thought I'd let you know :)

**Comment by iamjustkoi** [comment]
Shoot, that's a shame.
Thanks for the report! Really appreciate you looking into it a bit, too.
Will see what I can do. Busy next couple of weeks, but I'll try to see about stamping this out for good as soon as I can, hopefully!

**Comment by iamjustkoi** [comment]
Should be fixed for the most recent release! Yep. Definitely should be. No doubt.
(defs let me know if it pops up again, though)

**Comment by Ankilli** [comment]
But I'm not even sure if the "Cannot read property 'classList' of null"-error is the reason for the window pop-up because the error message appears with every card..
So then the Terminal is not giving me anything unfortunately :/

**Comment by iamjustkoi** [comment]
Shoot, sorry you're still running into this.

> So then the Terminal is not giving me anything unfortunately :/

Yeah, that's something to do with Anki itself, I'm pretty sure.

I'm having a really tough time reproducing it on my end, to be honest.
Would you mind re-sending your debug info and maybe also the add-on's meta file?
(Tools -> Add-ons -> Leech Toolkit -> View Files -> "meta.json")
On top of that, just wondering if you know if you're currently using the default deck as one of your decks or not? Maybe renamed?
Also one other thing you could try is potentially checking your database and removing empty cards under the Tools menu, just in case.

Again, sorry it's still sticking around for you so bad! I'll try to see if I can get this fixed/solved over the weekend.

**Comment by Ankilli** [comment]
1) Debug info:
    
    Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.14.1 PyQt 5.14.1
    Platform: Mac 12.6.2
    Flags: frz=True ao=True sv=3
    Add-ons, last update check: 2022-12-14 21:20:46
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    '' ['autoLearningSteps', 0, 'None', '']
    AMBOSS add-on ['0amboss_addon', 2022-06-27T18:14, 'None', '']
    AnKing Note Types Easy Customization ['952691989', 2022-11-22T19:37, 'None', '']
    Anki Simulator ['817108664', 2021-08-07T21:24, 'None', '']
    Anki Zoom ['538879081', 2020-04-04T02:20, 'v1.1.3', '']
    AnkiWebView Inspector ['31746032', 2022-04-08T21:44, 'None', '']
    Asset Manager ['656021484', 2021-08-29T23:07, 'None', '']
    Batch Editing ['291119185', 2019-06-02T20:47, 'None', '']
    BetterSearch ['1052724801', 2022-01-25T23:25, 'None', '']
    Closet For Anki ['272311064', 2022-08-12T10:27, 'None', '']
    Cloze Overlapper for Anki 21 ['109531687', 2021-01-12T04:12, 'None', '']
    Copy notes ['1566928056', 2021-12-24T20:56, 'None', '']
    Cross Profile Search and Import ['310394744', 2019-05-28T18:15, 'None', '']
    Custom Background Image and Gear Icon ['1210908941', 2022-11-28T19:08, 'None', mod]
    Customize Keyboard Shortcuts ['24411424', 2022-09-14T11:12, 'None', '']
    Deadline2 ['723639202', 2021-05-02T06:45, 'None', mod]
    Frozen Fields ['516643804', 2020-03-01T05:12, 'None', '']
    Image Occlusion Enhanced ['1374772155', 2022-04-09T09:15, 'None', '']
    Leaderboard ['41708974', 2022-05-12T11:46, 'None', mod]
    Learning Step and Review Interval Retention ['1949865265', 2022-08-28T22:21, 'None', '']
    Leech Toolkit ['368380974', 2022-12-13T20:57, 'None', '']
    Mini Format Pack ['295889520', 2018-07-24T19:45, 'None', '']
    More Decks Stats and Time Left ['1556734708', 2022-10-09T14:05, 'None', mod]
    Postpone cards review ['1152543397', 2021-02-13T17:47, 'None', '']
    Refocus Card when Reviewing 21 ['1642550423', 2018-09-19T16:14, 'None', '']
    Remaining time for Anki 21 ['1508357010', 2020-12-13T15:14, '20.12.13i151', mod]
    Removes Empty Note Types for 21 ['530953383', 2019-06-12T16:11, 'None', '']
    Reset Card Scheduling ['300884351', 2018-09-18T18:17, 'None', '']
    Resize images in editor ['1103084694', 2021-07-19T08:35, 'None', mod]
    Review Heatmap ['review_heatmap', 2020-04-30T15:23, 'None', '']
    Set Card Ease ['1387847178', 2022-11-17T19:41, 'None', mod]
    Special Fields ['1102281552', 2022-11-22T02:49, 'None', mod]
    Speed Focus Mode auto-alert auto-reveal auto-fail ['1046608507', 2019-06-02T11:11, 'None', '']
    Straight Reward ['957961234', 2022-03-31T21:37, 'None', '']
    Symbols As You Type ['2040501954', 2022-06-08T06:09, 'None', '']
    Transfer scheduling data from one card to another ['94685914', 2020-09-18T11:23, 'None', '']
    True Retention by Card Maturity ['923360400', 2017-08-29T21:00, 'None', '']
    Ze Add Note Id ['886709118', 2021-03-02T21:06, 'None', '']
    ZzLegacy Spelling Police ['1410276506', 2020-03-03T03:13, 'None', mod]
    autoLapseNewInterval  automatically adjust the new interval after a lapse ['372281481', 2022-09-28T09:26, 'None', mod]
    avgEase for Anki  2141 ['1129477042', 2021-06-27T13:58, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1046608507 1052724801 109531687 1102281552 1103084694 1129477042 1152543397 1210908941 1374772155 1387847178 1410276506 1508357010 1556734708 1566928056 1642550423 1949865265 2040501954 24411424 272311064 291119185 295889520 300884351 310394744 31746032 368380974 372281481 41708974 516643804 530953383 538879081 656021484 723639202 817108664 886709118 923360400 94685914 952691989 957961234
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Advanced Review Bottom Bar ['1136455830', 2022-09-29T15:31, 'None', mod]
    Auto Ease Factor ['1672712021', 2021-03-21T19:11, 'None', mod]
    ImageResizer ['1214357311', 2022-07-15T15:05, 'None', '']
    Legacy ReMemorize ['323586997', 2020-11-20T06:27, 'None', mod]
    Speed Focus Mode ['speed_focus_mode', 2019-06-29T00:35, 'None', '']
    True Retention ['613684242', 2017-11-19T21:43, 'None', '']

2) meta.json is attached :)

3) I don't know if I interpret "default deck" correctly but I only use decks I created myself or imported from other users^^
I don't use that deck that's called "Standard" where new cards go to if they aren't assigned to any existing deck already. I hope that is what you meant 😅

4) Checked my database, no empty cards :)

Btw. I'd have another guess that LeechToolkit is maybe interfering with the StraightReward-Addon. At least I noticed both showing message popups on the bottom left corner on the cards with that error message popping up. I will see how it goes if I deactivate StraightReward tomorrow, maybe it's coming from there :)

[meta.json.zip](https://github.com/iamjustkoi/LeechToolkit/files/10240856/meta.json.zip)

**Comment by iamjustkoi** [comment]
Oh, whoops, it actually looks like it's not as big of a problem as I thought! Didn't think about this, but it looks like you just have an option enabled for the default deck options group (might've been renamed standard, though) to move cards to a deck with the input set to nothing, right now.

If you go to the default Options group (Shift + Options, then select Default or could be "Standard") and uncheck the Move to Deck action/reset it to default, under the Leech Actions, you should be good to go!

If you want to override movement for decks that use that group, though, you can also set it back to itself, too.

I should probs put something in to warn about that happening and/or make it not move the cards when there's no input, to be honest. 

Either way, hope that solves it and wish you best!

**Comment by iamjustkoi** [comment]
Closing for now but let me know if something still pops up, again! 👍

**Comment by Ankilli** [comment]
Hey, thanks again for the quick reply and for sticking to it 😅

unfortunately the move to deck action is already set to default :/

Disabling the Straight Reward addon brought no luck but I noticed another thing.

When a card was failed once and then reversed on the next try I get a "Leech decreased! Leech reversed!"-message popping up in the bottom left corner. Is it meant to be like that? Or should it only show one of the messages? Because usually I only get the "Leech decreased!"-msg when I failed a card more than once before answering it correctly.
I guess would be that there is one message too much on the cards because I only get the NoteType:None-error on cards where the "Leech decreased! Leech reversed!"-msg. comes up as well..

Hope it helps :)

<img width="301" alt="grafik" src="https://user-images.githubusercontent.com/89978096/208129027-d0fe1856-e151-489d-b704-71e4c74a5978.png">

**Comment by iamjustkoi** [comment]
> Hey, thanks again for the quick reply and for sticking to it 😅

Defs!

> "Leech decreased! Leech reversed!"-msg

Thanks! Should be fixed with the last release! Had it sort-of figured out already, hopefully the quick update works out nicely + some compatibility updates for the recent Anki release with it.

Just in case, you might be checking something else or there might be some other issue, I edited the meta.json file to hopefully have everything setup without any problems (attached below). 
Try replacing your current meta with that one and see if that works out for you.

Wish you the best!

[meta.zip](https://github.com/iamjustkoi/LeechToolkit/files/10247038/meta.zip)

**Comment by Ankilli** [comment]
Hey there,
unfortunately it still persits ':D
I updated to the most recent version (thank you for the option to turn off notifications :) )
and changed th json file in my folder with yours. But unfortunately nothing changed and as I mentioned earlier the Terminal.app isn't giving me anything here.

Anyway nice holidays :)

**Comment by iamjustkoi** [comment]
Hey! Wanted to reply sooner but haven't had time/internet access for a bit, either way:

> thank you for the option to turn off notifications :)

No prob! :D

> unfortunately it still persists

Man, sorry this is still happening. I'll try a few more environments and test builds and see what I can do. Will reopen, for the time being.

> Anyway nice holidays :)

Thanks a bunch and same to you! Cheers! 😄

**Comment by iamjustkoi** [comment]
Took a bit longer than I wanted it to but I was able to get everything setup again, sort of, and ran some tests so hopefully this last version tackles this issue! (or at least makes it less noticeable...?)

**Comment by Ankilli** [comment]
Hey, thank you for sticking to it!
I'm afraid the issue still persists 😅

**Comment by iamjustkoi** [comment]
Heck, sorry, I'm having too many issues trying to reproduce this on my end!

It seems like it has something to do with an empty undo entry, or maybe an empty deck/card, there's definitely some empty...thing somewhere, but I can't seem to get the error to pop up given the settings and environment in the original post.

I might have to close this or put it in the `on-hold` or `wontfix` category, unless someone else runs into it, too, or I can find out where the issue might be popping up. 
If it happens regardless of any specific settings, though, then it seems like an undo-entry thing, all things considered.

Either way, sorry this is happening, appreciate the patience, and thanks for sticking with me on your end too!

I might be able to make a small patch that has an option to disable undo logging, near-future, but that might end up feeling a bit more frustrating, if I did, so will have to see.
I'll update the thread if anything changes, too, though.

**Comment by Ankilli** [comment]
no worries and thanks after all for sticking to it! :)

**Comment by Ankilli** [comment]
I found the reason.
The addon "FSRS4Anki Helper" is causing the issue. Probably because it interferes a lot with the scheduling.
I will write the creator as well to let him know, maybe it can get fixed^^
:)
